name: 'Substring Commit Message'
description: 'Extract string from last commit message'
inputs:
  pattern-to-search:  # id of input
    description: 'The pattern to look for in the commit message'
    required: true
    default: 'something'
outputs:
  match: # id of output
    description: 'The matched string or "null" if no match was found'
runs:
  using: 'node16'
  main: 'index.js'